### PR TITLE
feat: generalize Sherlock to integrate Prophet detection pipeline

### PR DESCRIPTION
**Pull request by hanxu12**
1. generalized and expanded Sherlock with a new anomaly detection pipeline, which uses Meta's Prophet for prediction
2. added query function for the Prophet Service to support Batch Query feature
3. added DetectorException to handle HTTP exceptions
4. added Prophet-related parameters/CLI arguments
5. refactored EgadsConfig to Detector Config; refactored EgadsResult to DetectorResult
6. optimized the original Egads detection pipeline (~12% speed up)
7. fixed original pipeline bug such that Sherlock generates an array of empty lists instead of nulls when the input source is empty
8. fixed original pipeline bug such that Sherlock runs user selected Time Series/Anomaly Detection models for cronJob/backfillJob
9. fixed original pipeline bug such that NaiveModel is working
10. modified web UI to correspond with backend changes
11. added Jupyter Notebooks to compare Egads/Prophet pipeline results ('forecaster_comparison' folder)
12. unit tests and comments; fix typos

### CODE REVIEW

**Comment by jigs1993** [comment]
@hanxu12  according to this [doc](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow), secrets are not passed to PR made from forked repo...hence the build is failing

**Comment by hanxu12** [comment]
> @hanxu12 according to this [doc](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow), secrets are not passed to PR made from forked repo...hence the build is failing

That is true. What action should I take? (e.g., create environment secrets on my side)

**Comment by jigs1993** [comment]
i changed the package publish on push to master only, can you try rebasing now @hanxu12

**Comment by hanxu12** [comment]
> i changed the package publish on push to master only, can you try rebasing now @hanxu12

Done. Thank you! :D

**Comment by jigs1993** [comment]
Hi @hanxu12 
just fixed the workflow again, can you rebase?

**Comment by hanxu12** [comment]
> Hi @hanxu12 just fixed the workflow again, can you rebase?

Thank you! Done and it builds successfully.

**Pull request merged**
